if: tag IS blank

language: node_js
node_js: lts/*
cache: 
  yarn: true
  directories:
    - ~/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add codecov
  - yarn global add firebase-tools
  - yarn install --frozen-lockfile
  - lerna bootstrap

script:
  - yarn library
  - yarn coverage
  - codecov
  - yarn coverage:cleanup
  - yarn build
  - yarn test:e2e:run

deploy:
  provider: script
  script: lerna run deploy --since
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE != *'chore(deps)'*

after_deploy: bash .travis/lernaVersion.sh

env:
  global:
  - secure: qqyO5TN+OnK6D3auk29IT2dbWbAt66Mn/HtcnqfuMwKyFVqhSRaRPetLlxjokMfpUaMSffQoP+WMC3Gq6cwxj7+ngIADC8eX7sloFaZ6KqR3xbrAoZbLU76d5EZ43KdGw/Zp6Z5jWkB8VI823omLtdNwvLm57gyb6DwomvH1JAE0cFnftRmugeWintwpmUffz0HsHwAqztYzd0EHBOGv+Q9D4Mggy5H48TpKhFaNHHD2Nc9Y9sMoZolNfW72pYjU04YNEi0QAo8YnkHdSSrPdV9WrfIE+Qb/DzrlUu1Xt9vra+Q5tKGhUwYKbZPKun6lF+9cZFv90EteIbpMGrn4kNB9RwbKmsXvXDW0Su+U2039meT+q6sT4vAIiTrJP83DL0uHxQJQQpZEI9KQyV2daQjRCdPlvfQRoTNmyfiT/ZnRUSo4ScTkKKEHMVN3d3yvhBQfPA9N2Qp/5adHagah/Ie1XlREFIIs/hKI/0LAbIz6d9n4aYprd2eCC3xIftkFKMBBHLYiAeomq54mlhhlwOuIa01EQ1lCScU1VRvqdh//OyOoN4cY+yitgAdWnnTWQT2LmyR47AnaNFyPRG2VkYM9DtqdVz9BctxKa7asC4g1lGOV8xFOt23KEm+1A1J26ducFRvvpNaav2GF8D1F4/Rv6WTyu3iCQHksYprYP5Y=
  - secure: Wc3Hee3ptsN3HFuySmE/Aiga/3P/3XL8kfkoInJSeRnAWQl7nhjmp7YiARqgN8/JcJ/XrQ/7MkQZD2XGjbA8CwWEWiv8M+EgLcym6YtkvwUPVRWFAq9JGGe5RzI6+EdksRDRB0mho4rWNyA//FFB+54wGad8C/jta9D4puE49a3iZy6NGZnxRRTiBTmGcYmH+ZF/hVXihCApvL1X6UrMRCL2AQzE8vGbgvA8WSBkAnYVQEtEhwm+2aWkxPxTe40R0p7yUhbppn24e2lByl69n1saKuL1eEu3O15sur8zqlyhOfPhpWy2h5IsGuz3xxC08KCyCX/NpbUWF+WrwxB486M1ZiHiHjZomWsh4aeTMdmCKv63ZHqTVOgpCv5Of7M1qZzxJkhbZ2aV5sdccJKsO/9wyI3r0oAgrFSA0nhFur3dn2GEaeKmFR9/HL65L1PCxLeqdQuyaYwdqPWdjC+9KVcfrZLoqjfXKPs1kE+eBQdMDorQGFApdylt+e6tAYJCVjjx4+EwrEjihdoVX/Sxv+aVE5TD2L27aZkS0qt0mUI1dzJ8cN8y0hhmqyzf/kjE3sWYcX9GnWjrRmyROZML3GjGctBPcC7io3no5eXtZ7tPohcw6qQUPMM8Gsn2M5JG4SdXABA61+PwGzdW5Jl/f1vSP5XtEFBW3cevoTnwZQk=
