language: node_js
node_js:
  - lts/*
cache: yarn
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
install:
  - yarn global add codecov
  - yarn global add firebase-tools
  - yarn global add lerna
  - lerna bootstrap
script:
  - yarn library:prod
  - lerna run coverage
  - codecov
  - lerna run coverage:cleanup
  - lerna run build
deploy:
  provider: script
  script: lerna run deploy
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: qqyO5TN+OnK6D3auk29IT2dbWbAt66Mn/HtcnqfuMwKyFVqhSRaRPetLlxjokMfpUaMSffQoP+WMC3Gq6cwxj7+ngIADC8eX7sloFaZ6KqR3xbrAoZbLU76d5EZ43KdGw/Zp6Z5jWkB8VI823omLtdNwvLm57gyb6DwomvH1JAE0cFnftRmugeWintwpmUffz0HsHwAqztYzd0EHBOGv+Q9D4Mggy5H48TpKhFaNHHD2Nc9Y9sMoZolNfW72pYjU04YNEi0QAo8YnkHdSSrPdV9WrfIE+Qb/DzrlUu1Xt9vra+Q5tKGhUwYKbZPKun6lF+9cZFv90EteIbpMGrn4kNB9RwbKmsXvXDW0Su+U2039meT+q6sT4vAIiTrJP83DL0uHxQJQQpZEI9KQyV2daQjRCdPlvfQRoTNmyfiT/ZnRUSo4ScTkKKEHMVN3d3yvhBQfPA9N2Qp/5adHagah/Ie1XlREFIIs/hKI/0LAbIz6d9n4aYprd2eCC3xIftkFKMBBHLYiAeomq54mlhhlwOuIa01EQ1lCScU1VRvqdh//OyOoN4cY+yitgAdWnnTWQT2LmyR47AnaNFyPRG2VkYM9DtqdVz9BctxKa7asC4g1lGOV8xFOt23KEm+1A1J26ducFRvvpNaav2GF8D1F4/Rv6WTyu3iCQHksYprYP5Y=
