// flow-typed signature: d593301931b9226888bbad63ea7e54a2
// flow-typed version: <<STUB>>/apollo-tracing_v^0.1.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-tracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-tracing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-tracing/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-tracing/lib/index.js' {
  declare module.exports: $Exports<'apollo-tracing/lib/index'>;
}
