// flow-typed signature: 2e30a354e66e5d8283f7fd2f17d7a7cc
// flow-typed version: <<STUB>>/nodemon-webpack-plugin_v3.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemon-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemon-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemon-webpack-plugin/cucumber' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/dist/webpack-utils' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/step_definitions/assertions' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/step_definitions/fileModifications' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/step_definitions/webpack' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/support/outputMonitoring' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/support/templates' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/support/tmpDir' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/features/support/webpackLauncher' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'nodemon-webpack-plugin/src/webpack-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemon-webpack-plugin/cucumber.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/cucumber'>;
}
declare module 'nodemon-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/dist/index'>;
}
declare module 'nodemon-webpack-plugin/dist/webpack-utils.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/dist/webpack-utils'>;
}
declare module 'nodemon-webpack-plugin/features/step_definitions/assertions.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/step_definitions/assertions'>;
}
declare module 'nodemon-webpack-plugin/features/step_definitions/fileModifications.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/step_definitions/fileModifications'>;
}
declare module 'nodemon-webpack-plugin/features/step_definitions/webpack.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/step_definitions/webpack'>;
}
declare module 'nodemon-webpack-plugin/features/support/outputMonitoring.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/support/outputMonitoring'>;
}
declare module 'nodemon-webpack-plugin/features/support/templates.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/support/templates'>;
}
declare module 'nodemon-webpack-plugin/features/support/tmpDir.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/support/tmpDir'>;
}
declare module 'nodemon-webpack-plugin/features/support/webpackLauncher.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/features/support/webpackLauncher'>;
}
declare module 'nodemon-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/src/index'>;
}
declare module 'nodemon-webpack-plugin/src/webpack-utils.js' {
  declare module.exports: $Exports<'nodemon-webpack-plugin/src/webpack-utils'>;
}
