// flow-typed signature: fa94d1f4e8b4cf7ce33a5fbe9251e592
// flow-typed version: <<STUB>>/react-router-config_v1.0.0-beta.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-config/es/index' {
  declare module.exports: any;
}

declare module 'react-router-config/es/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router-config/es/renderRoutes' {
  declare module.exports: any;
}

declare module 'react-router-config/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router-config/renderRoutes' {
  declare module.exports: any;
}

declare module 'react-router-config/umd/react-router-config' {
  declare module.exports: any;
}

declare module 'react-router-config/umd/react-router-config.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-config/es/index.js' {
  declare module.exports: $Exports<'react-router-config/es/index'>;
}
declare module 'react-router-config/es/matchRoutes.js' {
  declare module.exports: $Exports<'react-router-config/es/matchRoutes'>;
}
declare module 'react-router-config/es/renderRoutes.js' {
  declare module.exports: $Exports<'react-router-config/es/renderRoutes'>;
}
declare module 'react-router-config/index' {
  declare module.exports: $Exports<'react-router-config'>;
}
declare module 'react-router-config/index.js' {
  declare module.exports: $Exports<'react-router-config'>;
}
declare module 'react-router-config/matchRoutes.js' {
  declare module.exports: $Exports<'react-router-config/matchRoutes'>;
}
declare module 'react-router-config/renderRoutes.js' {
  declare module.exports: $Exports<'react-router-config/renderRoutes'>;
}
declare module 'react-router-config/umd/react-router-config.js' {
  declare module.exports: $Exports<'react-router-config/umd/react-router-config'>;
}
declare module 'react-router-config/umd/react-router-config.min.js' {
  declare module.exports: $Exports<'react-router-config/umd/react-router-config.min'>;
}
