// flow-typed signature: 9acfa4908f3ad06e19c0a38910ae0e7c
// flow-typed version: <<STUB>>/sanitize.css_v7.0.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
