/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface MaButton {
    'color': string;
    'type': string;
  }
  interface MaPauseIcon {}
  interface MaPlayIcon {}
  interface MaUndoIcon {}
}

declare namespace LocalJSX {
  interface MaButton extends JSXBase.HTMLAttributes {
    'color'?: string;
    'type'?: string;
  }
  interface MaPauseIcon extends JSXBase.HTMLAttributes {}
  interface MaPlayIcon extends JSXBase.HTMLAttributes {}
  interface MaUndoIcon extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'MaButton': Components.MaButton;
    'MaPauseIcon': Components.MaPauseIcon;
    'MaPlayIcon': Components.MaPlayIcon;
    'MaUndoIcon': Components.MaUndoIcon;
  }

  interface IntrinsicElements {
    'MaButton': LocalJSX.MaButton;
    'MaPauseIcon': LocalJSX.MaPauseIcon;
    'MaPlayIcon': LocalJSX.MaPlayIcon;
    'MaUndoIcon': LocalJSX.MaUndoIcon;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {

  interface HTMLMaButtonElement extends Components.MaButton, HTMLStencilElement {}
  var HTMLMaButtonElement: {
    prototype: HTMLMaButtonElement;
    new (): HTMLMaButtonElement;
  };

  interface HTMLMaPauseIconElement extends Components.MaPauseIcon, HTMLStencilElement {}
  var HTMLMaPauseIconElement: {
    prototype: HTMLMaPauseIconElement;
    new (): HTMLMaPauseIconElement;
  };

  interface HTMLMaPlayIconElement extends Components.MaPlayIcon, HTMLStencilElement {}
  var HTMLMaPlayIconElement: {
    prototype: HTMLMaPlayIconElement;
    new (): HTMLMaPlayIconElement;
  };

  interface HTMLMaUndoIconElement extends Components.MaUndoIcon, HTMLStencilElement {}
  var HTMLMaUndoIconElement: {
    prototype: HTMLMaUndoIconElement;
    new (): HTMLMaUndoIconElement;
  };
  interface HTMLElementTagNameMap {
    'ma-button': HTMLMaButtonElement
    'ma-pause-icon': HTMLMaPauseIconElement
    'ma-play-icon': HTMLMaPlayIconElement
    'ma-undo-icon': HTMLMaUndoIconElement
  }

  interface ElementTagNameMap {
    'ma-button': HTMLMaButtonElement;
    'ma-pause-icon': HTMLMaPauseIconElement;
    'ma-play-icon': HTMLMaPlayIconElement;
    'ma-undo-icon': HTMLMaUndoIconElement;
  }
}

