/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MaButton {
    'color': string;
    'type': string;
  }
  interface MaPauseIcon {}
  interface MaPlayIcon {}
  interface MaUndoIcon {}
}

declare global {


  interface HTMLMaButtonElement extends Components.MaButton, HTMLStencilElement {}
  var HTMLMaButtonElement: {
    prototype: HTMLMaButtonElement;
    new (): HTMLMaButtonElement;
  };

  interface HTMLMaPauseIconElement extends Components.MaPauseIcon, HTMLStencilElement {}
  var HTMLMaPauseIconElement: {
    prototype: HTMLMaPauseIconElement;
    new (): HTMLMaPauseIconElement;
  };

  interface HTMLMaPlayIconElement extends Components.MaPlayIcon, HTMLStencilElement {}
  var HTMLMaPlayIconElement: {
    prototype: HTMLMaPlayIconElement;
    new (): HTMLMaPlayIconElement;
  };

  interface HTMLMaUndoIconElement extends Components.MaUndoIcon, HTMLStencilElement {}
  var HTMLMaUndoIconElement: {
    prototype: HTMLMaUndoIconElement;
    new (): HTMLMaUndoIconElement;
  };
  interface HTMLElementTagNameMap {
    'ma-button': HTMLMaButtonElement;
    'ma-pause-icon': HTMLMaPauseIconElement;
    'ma-play-icon': HTMLMaPlayIconElement;
    'ma-undo-icon': HTMLMaUndoIconElement;
  }
}

declare namespace LocalJSX {
  interface MaButton extends JSXBase.HTMLAttributes<HTMLMaButtonElement> {
    'color'?: string;
    'type'?: string;
  }
  interface MaPauseIcon extends JSXBase.HTMLAttributes<HTMLMaPauseIconElement> {}
  interface MaPlayIcon extends JSXBase.HTMLAttributes<HTMLMaPlayIconElement> {}
  interface MaUndoIcon extends JSXBase.HTMLAttributes<HTMLMaUndoIconElement> {}

  interface IntrinsicElements {
    'ma-button': MaButton;
    'ma-pause-icon': MaPauseIcon;
    'ma-play-icon': MaPlayIcon;
    'ma-undo-icon': MaUndoIcon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


