/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MaButton {
    'color': string;
    'type': string;
  }
  interface MaIcons {
    'name': string;
  }
}

declare global {


  interface HTMLMaButtonElement extends Components.MaButton, HTMLStencilElement {}
  var HTMLMaButtonElement: {
    prototype: HTMLMaButtonElement;
    new (): HTMLMaButtonElement;
  };

  interface HTMLMaIconsElement extends Components.MaIcons, HTMLStencilElement {}
  var HTMLMaIconsElement: {
    prototype: HTMLMaIconsElement;
    new (): HTMLMaIconsElement;
  };
  interface HTMLElementTagNameMap {
    'ma-button': HTMLMaButtonElement;
    'ma-icons': HTMLMaIconsElement;
  }
}

declare namespace LocalJSX {
  interface MaButton extends JSXBase.HTMLAttributes<HTMLMaButtonElement> {
    'color'?: string;
    'type'?: string;
  }
  interface MaIcons extends JSXBase.HTMLAttributes<HTMLMaIconsElement> {
    'name'?: string;
  }

  interface IntrinsicElements {
    'ma-button': MaButton;
    'ma-icons': MaIcons;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


