// flow-typed signature: 49914edf68d111703ebb5882b4a6ee4b
// flow-typed version: <<STUB>>/@mattailes/common_v1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mattailes/common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mattailes/common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mattailes/common/components/Button/Button' {
  declare module.exports: any;
}

declare module '@mattailes/common/components/Button/index' {
  declare module.exports: any;
}

declare module '@mattailes/common/components/index' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Film' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/index' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Person' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Planet' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Species' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Starship' {
  declare module.exports: any;
}

declare module '@mattailes/common/types/StarWars/Vehicle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mattailes/common/components/Button/Button.js' {
  declare module.exports: $Exports<'@mattailes/common/components/Button/Button'>;
}
declare module '@mattailes/common/components/Button/index.js' {
  declare module.exports: $Exports<'@mattailes/common/components/Button/index'>;
}
declare module '@mattailes/common/components/index.js' {
  declare module.exports: $Exports<'@mattailes/common/components/index'>;
}
declare module '@mattailes/common/types/StarWars/Film.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Film'>;
}
declare module '@mattailes/common/types/StarWars/index.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/index'>;
}
declare module '@mattailes/common/types/StarWars/Person.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Person'>;
}
declare module '@mattailes/common/types/StarWars/Planet.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Planet'>;
}
declare module '@mattailes/common/types/StarWars/Species.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Species'>;
}
declare module '@mattailes/common/types/StarWars/Starship.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Starship'>;
}
declare module '@mattailes/common/types/StarWars/Vehicle.js' {
  declare module.exports: $Exports<'@mattailes/common/types/StarWars/Vehicle'>;
}
