// flow-typed signature: 77bbcdee834fa12be0f8bac70ba82d27
// flow-typed version: <<STUB>>/@mattailes/types_v1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mattailes/types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mattailes/types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mattailes/types/StarWars/Film' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/index' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/Person' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/Planet' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/Species' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/Starship' {
  declare module.exports: any;
}

declare module '@mattailes/types/StarWars/Vehicle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mattailes/types/index' {
  declare module.exports: $Exports<'@mattailes/types'>;
}
declare module '@mattailes/types/index.js' {
  declare module.exports: $Exports<'@mattailes/types'>;
}
declare module '@mattailes/types/StarWars/Film.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Film'>;
}
declare module '@mattailes/types/StarWars/index.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/index'>;
}
declare module '@mattailes/types/StarWars/Person.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Person'>;
}
declare module '@mattailes/types/StarWars/Planet.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Planet'>;
}
declare module '@mattailes/types/StarWars/Species.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Species'>;
}
declare module '@mattailes/types/StarWars/Starship.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Starship'>;
}
declare module '@mattailes/types/StarWars/Vehicle.js' {
  declare module.exports: $Exports<'@mattailes/types/StarWars/Vehicle'>;
}
