// flow-typed signature: 487e0d8cf279be5919c4a3b39fa585d1
// flow-typed version: <<STUB>>/@mattailes/ui_v1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mattailes/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mattailes/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mattailes/ui/build/index' {
  declare module.exports: any;
}

declare module '@mattailes/ui/src/components/Button/Button' {
  declare module.exports: any;
}

declare module '@mattailes/ui/src/components/Button/index' {
  declare module.exports: any;
}

declare module '@mattailes/ui/src/index' {
  declare module.exports: any;
}

declare module '@mattailes/ui/src/theme/index' {
  declare module.exports: any;
}

declare module '@mattailes/ui/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mattailes/ui/build/index.js' {
  declare module.exports: $Exports<'@mattailes/ui/build/index'>;
}
declare module '@mattailes/ui/src/components/Button/Button.js' {
  declare module.exports: $Exports<'@mattailes/ui/src/components/Button/Button'>;
}
declare module '@mattailes/ui/src/components/Button/index.js' {
  declare module.exports: $Exports<'@mattailes/ui/src/components/Button/index'>;
}
declare module '@mattailes/ui/src/index.js' {
  declare module.exports: $Exports<'@mattailes/ui/src/index'>;
}
declare module '@mattailes/ui/src/theme/index.js' {
  declare module.exports: $Exports<'@mattailes/ui/src/theme/index'>;
}
declare module '@mattailes/ui/webpack.config.js' {
  declare module.exports: $Exports<'@mattailes/ui/webpack.config'>;
}
