// flow-typed signature: 3a2e5514e3cb7a99277de9bc23c03522
// flow-typed version: <<STUB>>/@mattailes/ui_v1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mattailes/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mattailes/ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mattailes/ui/Button/Button' {
  declare module.exports: any;
}

declare module '@mattailes/ui/Button/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mattailes/ui/Button/Button.js' {
  declare module.exports: $Exports<'@mattailes/ui/Button/Button'>;
}
declare module '@mattailes/ui/Button/index.js' {
  declare module.exports: $Exports<'@mattailes/ui/Button/index'>;
}
declare module '@mattailes/ui/index' {
  declare module.exports: $Exports<'@mattailes/ui'>;
}
declare module '@mattailes/ui/index.js' {
  declare module.exports: $Exports<'@mattailes/ui'>;
}
