// flow-typed signature: b77b248d78d97087de26be07d84dd4d0
// flow-typed version: <<STUB>>/@storybook/addon-centered_v4.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-centered'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-centered' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-centered/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/helpers/json2CSS' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/svelte' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/dist/vue' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/angular' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/ember' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/helpers/json2CSS' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/html' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/mithril' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/styles' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/svelte' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/src/vue' {
  declare module.exports: any;
}

declare module '@storybook/addon-centered/svelte' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-centered/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/angular'>;
}
declare module '@storybook/addon-centered/dist/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/angular'>;
}
declare module '@storybook/addon-centered/dist/ember.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/ember'>;
}
declare module '@storybook/addon-centered/dist/helpers/json2CSS.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/helpers/json2CSS'>;
}
declare module '@storybook/addon-centered/dist/html.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/html'>;
}
declare module '@storybook/addon-centered/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/index'>;
}
declare module '@storybook/addon-centered/dist/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/mithril'>;
}
declare module '@storybook/addon-centered/dist/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/react'>;
}
declare module '@storybook/addon-centered/dist/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/styles'>;
}
declare module '@storybook/addon-centered/dist/svelte.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/svelte'>;
}
declare module '@storybook/addon-centered/dist/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/dist/vue'>;
}
declare module '@storybook/addon-centered/ember.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/ember'>;
}
declare module '@storybook/addon-centered/html.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/html'>;
}
declare module '@storybook/addon-centered/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/mithril'>;
}
declare module '@storybook/addon-centered/src/angular.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/angular'>;
}
declare module '@storybook/addon-centered/src/ember.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/ember'>;
}
declare module '@storybook/addon-centered/src/helpers/json2CSS.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/helpers/json2CSS'>;
}
declare module '@storybook/addon-centered/src/html.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/html'>;
}
declare module '@storybook/addon-centered/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/index'>;
}
declare module '@storybook/addon-centered/src/mithril.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/mithril'>;
}
declare module '@storybook/addon-centered/src/react.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/react'>;
}
declare module '@storybook/addon-centered/src/styles.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/styles'>;
}
declare module '@storybook/addon-centered/src/svelte.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/svelte'>;
}
declare module '@storybook/addon-centered/src/vue.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/src/vue'>;
}
declare module '@storybook/addon-centered/svelte.js' {
  declare module.exports: $Exports<'@storybook/addon-centered/svelte'>;
}
