// flow-typed signature: f350da88c6b3b00bf573eade38663616
// flow-typed version: <<STUB>>/@storybook/components_v4.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/components/dist/addon_panel/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/addon_panel/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/addon_panel/index.test' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/field' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/form.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/input' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/header/header' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/header/header.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/header/header.test' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/highlight_button' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icons/chevronRight' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icons/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/desktop' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/desktop.test' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/dimensions' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/layout/mobile' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/navigation/MenuLink' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/navigation/MenuLink.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/navigation/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/navigation/RoutedLink.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/navigation/RoutedLink.test' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/panel_actionbar/panel_actionbar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/panel_actionbar/panel_actionbar.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/placeholder/placeholder' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/table/cell' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/table/table' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/theme' {
  declare module.exports: any;
}

declare module '@storybook/components/src/addon_panel/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/addon_panel/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/addon_panel/index.test' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/field' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/form.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/input' {
  declare module.exports: any;
}

declare module '@storybook/components/src/header/header' {
  declare module.exports: any;
}

declare module '@storybook/components/src/header/header.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/header/header.test' {
  declare module.exports: any;
}

declare module '@storybook/components/src/highlight_button' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icons/chevronRight' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icons/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/desktop' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/desktop.test' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/dimensions' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/layout/mobile' {
  declare module.exports: any;
}

declare module '@storybook/components/src/navigation/MenuLink' {
  declare module.exports: any;
}

declare module '@storybook/components/src/navigation/MenuLink.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/navigation/RoutedLink' {
  declare module.exports: any;
}

declare module '@storybook/components/src/navigation/RoutedLink.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/navigation/RoutedLink.test' {
  declare module.exports: any;
}

declare module '@storybook/components/src/panel_actionbar/panel_actionbar' {
  declare module.exports: any;
}

declare module '@storybook/components/src/panel_actionbar/panel_actionbar.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/placeholder/placeholder' {
  declare module.exports: any;
}

declare module '@storybook/components/src/table/cell' {
  declare module.exports: any;
}

declare module '@storybook/components/src/table/table' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tabs/tabs' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/components/dist/addon_panel/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/addon_panel/index'>;
}
declare module '@storybook/components/dist/addon_panel/index.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/addon_panel/index.stories'>;
}
declare module '@storybook/components/dist/addon_panel/index.test.js' {
  declare module.exports: $Exports<'@storybook/components/dist/addon_panel/index.test'>;
}
declare module '@storybook/components/dist/form/field.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/field'>;
}
declare module '@storybook/components/dist/form/form.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/form.stories'>;
}
declare module '@storybook/components/dist/form/input.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/input'>;
}
declare module '@storybook/components/dist/header/header.js' {
  declare module.exports: $Exports<'@storybook/components/dist/header/header'>;
}
declare module '@storybook/components/dist/header/header.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/header/header.stories'>;
}
declare module '@storybook/components/dist/header/header.test.js' {
  declare module.exports: $Exports<'@storybook/components/dist/header/header.test'>;
}
declare module '@storybook/components/dist/highlight_button.js' {
  declare module.exports: $Exports<'@storybook/components/dist/highlight_button'>;
}
declare module '@storybook/components/dist/icons/chevronRight.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icons/chevronRight'>;
}
declare module '@storybook/components/dist/icons/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icons/index'>;
}
declare module '@storybook/components/dist/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/index'>;
}
declare module '@storybook/components/dist/layout/desktop.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/desktop'>;
}
declare module '@storybook/components/dist/layout/desktop.test.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/desktop.test'>;
}
declare module '@storybook/components/dist/layout/dimensions.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/dimensions'>;
}
declare module '@storybook/components/dist/layout/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/index'>;
}
declare module '@storybook/components/dist/layout/index.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/index.stories'>;
}
declare module '@storybook/components/dist/layout/mobile.js' {
  declare module.exports: $Exports<'@storybook/components/dist/layout/mobile'>;
}
declare module '@storybook/components/dist/navigation/MenuLink.js' {
  declare module.exports: $Exports<'@storybook/components/dist/navigation/MenuLink'>;
}
declare module '@storybook/components/dist/navigation/MenuLink.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/navigation/MenuLink.stories'>;
}
declare module '@storybook/components/dist/navigation/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/components/dist/navigation/RoutedLink'>;
}
declare module '@storybook/components/dist/navigation/RoutedLink.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/navigation/RoutedLink.stories'>;
}
declare module '@storybook/components/dist/navigation/RoutedLink.test.js' {
  declare module.exports: $Exports<'@storybook/components/dist/navigation/RoutedLink.test'>;
}
declare module '@storybook/components/dist/panel_actionbar/panel_actionbar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/panel_actionbar/panel_actionbar'>;
}
declare module '@storybook/components/dist/panel_actionbar/panel_actionbar.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/panel_actionbar/panel_actionbar.stories'>;
}
declare module '@storybook/components/dist/placeholder/placeholder.js' {
  declare module.exports: $Exports<'@storybook/components/dist/placeholder/placeholder'>;
}
declare module '@storybook/components/dist/table/cell.js' {
  declare module.exports: $Exports<'@storybook/components/dist/table/cell'>;
}
declare module '@storybook/components/dist/table/table.js' {
  declare module.exports: $Exports<'@storybook/components/dist/table/table'>;
}
declare module '@storybook/components/dist/tabs/tabs.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs'>;
}
declare module '@storybook/components/dist/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs.stories'>;
}
declare module '@storybook/components/dist/theme.js' {
  declare module.exports: $Exports<'@storybook/components/dist/theme'>;
}
declare module '@storybook/components/src/addon_panel/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/addon_panel/index'>;
}
declare module '@storybook/components/src/addon_panel/index.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/addon_panel/index.stories'>;
}
declare module '@storybook/components/src/addon_panel/index.test.js' {
  declare module.exports: $Exports<'@storybook/components/src/addon_panel/index.test'>;
}
declare module '@storybook/components/src/form/field.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/field'>;
}
declare module '@storybook/components/src/form/form.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/form.stories'>;
}
declare module '@storybook/components/src/form/input.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/input'>;
}
declare module '@storybook/components/src/header/header.js' {
  declare module.exports: $Exports<'@storybook/components/src/header/header'>;
}
declare module '@storybook/components/src/header/header.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/header/header.stories'>;
}
declare module '@storybook/components/src/header/header.test.js' {
  declare module.exports: $Exports<'@storybook/components/src/header/header.test'>;
}
declare module '@storybook/components/src/highlight_button.js' {
  declare module.exports: $Exports<'@storybook/components/src/highlight_button'>;
}
declare module '@storybook/components/src/icons/chevronRight.js' {
  declare module.exports: $Exports<'@storybook/components/src/icons/chevronRight'>;
}
declare module '@storybook/components/src/icons/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/icons/index'>;
}
declare module '@storybook/components/src/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/index'>;
}
declare module '@storybook/components/src/layout/desktop.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/desktop'>;
}
declare module '@storybook/components/src/layout/desktop.test.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/desktop.test'>;
}
declare module '@storybook/components/src/layout/dimensions.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/dimensions'>;
}
declare module '@storybook/components/src/layout/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/index'>;
}
declare module '@storybook/components/src/layout/index.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/index.stories'>;
}
declare module '@storybook/components/src/layout/mobile.js' {
  declare module.exports: $Exports<'@storybook/components/src/layout/mobile'>;
}
declare module '@storybook/components/src/navigation/MenuLink.js' {
  declare module.exports: $Exports<'@storybook/components/src/navigation/MenuLink'>;
}
declare module '@storybook/components/src/navigation/MenuLink.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/navigation/MenuLink.stories'>;
}
declare module '@storybook/components/src/navigation/RoutedLink.js' {
  declare module.exports: $Exports<'@storybook/components/src/navigation/RoutedLink'>;
}
declare module '@storybook/components/src/navigation/RoutedLink.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/navigation/RoutedLink.stories'>;
}
declare module '@storybook/components/src/navigation/RoutedLink.test.js' {
  declare module.exports: $Exports<'@storybook/components/src/navigation/RoutedLink.test'>;
}
declare module '@storybook/components/src/panel_actionbar/panel_actionbar.js' {
  declare module.exports: $Exports<'@storybook/components/src/panel_actionbar/panel_actionbar'>;
}
declare module '@storybook/components/src/panel_actionbar/panel_actionbar.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/panel_actionbar/panel_actionbar.stories'>;
}
declare module '@storybook/components/src/placeholder/placeholder.js' {
  declare module.exports: $Exports<'@storybook/components/src/placeholder/placeholder'>;
}
declare module '@storybook/components/src/table/cell.js' {
  declare module.exports: $Exports<'@storybook/components/src/table/cell'>;
}
declare module '@storybook/components/src/table/table.js' {
  declare module.exports: $Exports<'@storybook/components/src/table/table'>;
}
declare module '@storybook/components/src/tabs/tabs.js' {
  declare module.exports: $Exports<'@storybook/components/src/tabs/tabs'>;
}
declare module '@storybook/components/src/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tabs/tabs.stories'>;
}
declare module '@storybook/components/src/theme.js' {
  declare module.exports: $Exports<'@storybook/components/src/theme'>;
}
