/* eslint-disable camelcase */
/** Declaration file generated by dts-gen */

declare const typography_theme_de_young: {
  default: {
    baseFontSize: string
    baseLineHeight: number
    bodyColor: string
    bodyFontFamily: string[]
    bodyWeight: number
    boldWeight: number
    googleFonts: {
      name: string
      styles: string[]
    }[]
    headerColor: string
    headerFontFamily: string[]
    headerWeight: number
    overrideStyles: any
    title: string
  }
}

export = typography_theme_de_young
